postgresql:
  image: postgres:9.1
  ports:
    - 5432:5432
  environment:
    - POSTGRES_DB=sonar
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

sonarqube:
  image: orangesignal/sonarqube:4.1.2
  links:
    - postgresql:db
  ports:
    - 9000:9000
  environment:
    - DB_NAME=sonar
    - DB_USER=sonar
    - DB_PASS=sonar
