postgresql:
  image: postgres:9.3
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=sonar
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

sonarqube:
  image: orangesignal/sonarqube:5.0.1
  links:
    - postgresql:db
  ports:
    - "9000:9000"
  environment:
    - DB_NAME=sonar
    - DB_USER=sonar
    - DB_PASS=sonar
